import test from 'node:test';import assert from 'node:assert/strict';
import {FlyBody,PROFILE,hoverTrim,meanWingForces,wingForces,rotate,length} from '../src/biology/model.js';
import {FlightExperiment} from '../src/biology/experiment.js';
import {visualSample,BiologicalInsect} from '../src/biology/insect.js';
import {Environment} from '../src/core/environment.js';
import {config} from '../src/core/world.js';
import {Learner} from '../src/learning/dqn.js';
const run=(body,seconds,goal=[0,0,0])=>{for(let i=0;i<Math.round(seconds/.005);i++)body.step(.005,goal);return body.snapshot();};
const experiment=(e,seconds)=>{for(let i=0;i<Math.round(seconds/.002);i++)e.step(.002);return e.snapshot();};
const ACT={amplitude:hoverTrim(),roll:0,pitch:0,yaw:0};
test('published reference dimensions and units are explicit',()=>{assert.equal(PROFILE.mass,.983e-6);assert.equal(PROFILE.frequency,218);assert.equal(PROFILE.span,.00604);});
test('trim solves cycle-average lift equal to weight without altering gravity',()=>{const f=meanWingForces(ACT);assert.ok(Math.abs(f.force[1]/(PROFILE.mass*9.81)-1)<1e-6);assert.ok(Math.abs(f.force[0])<1e-12);assert.ok(Math.abs(f.force[2])<1e-12);assert.ok(f.power>0);});
test('symmetric wings have zero cycle-average torque',()=>{assert.ok(length(meanWingForces(ACT).torque)<1e-15);});
test('asymmetric wing commands create roll, pitch, yaw moments with correct signs',()=>{assert.ok(meanWingForces({...ACT,roll:.05}).torque[2]>0);assert.ok(meanWingForces({...ACT,pitch:.05}).torque[0]<0);assert.ok(meanWingForces({...ACT,yaw:.05}).torque[1]>0);});
test('wing force varies within the beat; no constant artificial hover force',()=>{assert.ok(wingForces(0,ACT).force[1]>wingForces(Math.PI/2,ACT).force[1]+1e-6);});
test('hover remains bounded for two seconds with unit quaternion',()=>{const s=run(new FlyBody(),2);assert.ok(Math.abs(s.p[1]-1.5)<.02);assert.ok(length([s.p[0],s.p[2]])<.02);assert.ok(Math.abs(Math.hypot(...s.q)-1)<1e-10);assert.ok(s.steps>9000);});
test('wing shutdown causes gravity-driven descent',()=>{const b=new FlyBody();b.wingsEnabled=false;const s=run(b,.2);assert.ok(s.p[1]<1.35);assert.equal(s.lift,0);assert.ok(s.v[1]<-1);});
test('force-driven body can steer laterally, not just replay forward flight',()=>{const s=run(new FlyBody(),1,[.3,0,0]);assert.ok(s.p[0]>.10);assert.ok(Math.abs(s.p[1]-1.5)<.05);assert.ok(s.tilt<.4);});
test('half timestep gives consistent one-second endpoint',()=>{const a=run(new FlyBody({dt:.0002}),1,[.2,0,.1]),b=run(new FlyBody({dt:.0001}),1,[.2,0,.1]);assert.ok(length(a.p.map((x,i)=>x-b.p[i]))<.003);});
test('frequency and mass experiments remain bounded across documented ranges',()=>{for(const frequency of [196,240])for(const massScale of [.7,1.3]){const s=run(new FlyBody({frequency,massScale}),.5);assert.ok(Math.abs(s.p[1]-1.5)<.05);assert.ok(s.tilt<.2);}});
test('visual expansion responds to an approaching object',()=>{const b=new FlyBody();const a=visualSample(b,{p:[1,1.5,0],radius:.1},[],0);const s=visualSample(b,{p:[.8,1.5,0],radius:.1},[],.02,a);assert.ok(s.expansion>0);assert.ok(s.bearing[0]>.99);});
test('occlusion prevents a visible threat cue',()=>{const s=visualSample(new FlyBody(),{p:[1,1.5,0]},[{p:[.5,1.5,0],size:[.1,1,1]}],0);assert.equal(s.visible,false);assert.equal(s.angularSize,0);});
test('delayed vision does not trigger escape before sensory delivery',()=>{const e=new FlightExperiment();e.stimulus('loom');experiment(e,.02);assert.equal(e.insect.events,0);});
test('unrehearsed left and right looms produce opposite reactive escapes',()=>{const positions=[];for(const side of [-1,1]){const e=new FlightExperiment();experiment(e,.074);e.stimulus('loom',side);experiment(e,.4);assert.ok(e.insect.events>0);positions.push(e.insect.p[0]);}assert.ok(positions[0]>.01);assert.ok(positions[1]<-.01);});
test('visual ablation removes visual escape but does not disable flight',()=>{const e=new FlightExperiment({vision:false});e.stimulus('loom');experiment(e,.5);assert.equal(e.insect.events,0);assert.ok(Math.abs(e.insect.p[0])<.002);assert.ok(e.insect.body.liftMean>0);});
test('a physical gust still affects the fly with vision disabled',()=>{const e=new FlightExperiment({vision:false});e.stimulus('gust');experiment(e,.12);assert.ok(e.insect.p[0]>.001);});
test('rate-feedback stabilizer recovers from roll impulse',()=>{const e=new FlightExperiment();e.stimulus('roll');const s=experiment(e,.8);assert.ok(s.bio.tilt<.1);assert.ok(Math.abs(s.bio.p[1]-1.5)<.03);});
test('biological experiment export retains configuration, stimuli and actual physics',()=>{const e=new FlightExperiment({frequency:220});e.stimulus('gust');experiment(e,.02);const x=e.export();assert.equal(x.schema,'mosquito-drone-lab/biological-experiment@1');assert.equal(x.config.frequency,220);assert.equal(x.events[0].type,'gust');assert.ok(x.trace.length>2);assert.ok(x.trace[0].q);});
test('biological opponent is seeded and reproducible',()=>{const a=new Environment({insectModel:'biological'}),b=new Environment({insectModel:'biological'});for(let i=0;i<5;i++){a.step(0);b.step(0);}assert.deepEqual(a.snapshot(),b.snapshot());});
test('drone observation dimension remains 19 and contains no insect internal state',()=>{const e=new Environment({insectModel:'biological'});e.step(0);assert.equal(e.observation().length,19);assert.ok(e.snapshot().insect.bio);assert.equal(e.snapshot().electrical.enabled,false);});
test('drone learner updates against the independent biological opponent',()=>{const learner=new Learner(17),e=new Environment({insectModel:'biological',duration:5});for(let i=0;i<80;i++){if(e.done)e.reset({...e.config,seed:e.config.seed+1});const s=e.observation(),a=learner.choose(s,.3),r=e.step(a);learner.remember(s,a,r.reward,r.observation,r.terminated||r.truncated);}assert.ok(learner.updates>0);assert.equal(e.insect.body.controller,true);});
test('insect obstacle contact is recorded, not silently bounced',()=>{const fly=new BiologicalInsect([0,1.5,0],1);fly.step(.002,{p:[99,99,99]},[{p:[0,1.5,0],size:[1,1,1]}],{agility:0,wind:0},0);assert.equal(fly.collision,true);});
test('invalid physics inputs are rejected and exposed config is bounded',()=>{assert.throws(()=>new FlyBody({dt:1}));assert.throws(()=>new FlyBody({massScale:NaN}));assert.equal(config({bioFrequency:1000,bioMassScale:0}).bioFrequency,240);assert.equal(config({bioMassScale:0}).bioMassScale,.7);});

test('biological snapshots cannot mutate internal wing forces',()=>{const b=new FlyBody();b.step(.002);const before=b.snapshot().wings[0].force[0],s=b.snapshot();s.wings[0].force[0]=999;assert.equal(b.snapshot().wings[0].force[0],before);});
