import test from 'node:test';import assert from 'node:assert/strict';
import {ConnectomeLIF} from '../src/neural/engine.js';import {decodeConnectome} from '../src/neural/assets.js';import {Environment} from '../src/core/environment.js';import {config} from '../src/core/world.js';
function graph(){return {n:3,m:2,offsets:new Uint32Array([0,1,2,2]),post:new Uint32Array([1,2]),weight:new Uint32Array([300,300]),sign:new Int32Array([1,1,-1]),ids:new Uint32Array([1,2,3]),coordinates:new Float32Array(9),manifest:{neurons:3,connections:2,synapses:600,groups:{}}};}
function binary(g){const b=new ArrayBuffer(16+4*(g.n+1)+8*g.m+20*g.n),d=new DataView(b);d.setUint32(0,0x534e434d,true);d.setUint32(4,1,true);d.setUint32(8,g.n,true);d.setUint32(12,g.m,true);let p=16;for(const a of [g.offsets,g.post,g.weight,g.ids,g.sign,g.coordinates]){new Uint8Array(b,p,a.byteLength).set(new Uint8Array(a.buffer));p+=a.byteLength;}return b;}
test('full graph binary validates census, positive weights, CSR and exact byte length',()=>{const g=graph(),b=binary(g);assert.equal(decodeConnectome(b,g.manifest).m,2);assert.throws(()=>decodeConnectome(b.slice(0,-4),g.manifest));assert.throws(()=>decodeConnectome(b,{...g.manifest,neurons:4}));const corrupt=binary(g);new Uint32Array(corrupt,32,2)[0]=999;assert.throws(()=>decodeConnectome(corrupt,g.manifest));});
test('resting graph stays silent without invented spontaneous activity',()=>{const n=new ConnectomeLIF(graph());for(let i=0;i<100;i++)n.step();assert.equal(n.totalSpikes,0);assert.equal(n.summary().neurons,3);});
test('spikes propagate through the delayed real-edge mechanism',()=>{const n=new ConnectomeLIF(graph());n.stimulate(0);n.step();assert.equal(n.counts[0],1);for(let i=0;i<3;i++)n.step();assert.equal(n.g[1],0);n.step();assert.ok(n.g[1]>0);for(let i=0;i<70;i++)n.step();assert.ok(n.counts[1]>0&&n.counts[2]>0);});
test('synaptic disconnection preserves sensory spikes but eliminates downstream output',()=>{const n=new ConnectomeLIF(graph());n.transmissionEnabled=false;n.stimulate(0);for(let i=0;i<80;i++)n.step();assert.equal(n.counts[0],1);assert.equal(n.counts[2],0);});
test('lesioned neurons cannot spike or transmit, including pending arrivals',()=>{const n=new ConnectomeLIF(graph());n.lesion([1]);n.stimulate(0);for(let i=0;i<80;i++)n.step();assert.equal(n.counts[1],0);assert.equal(n.counts[2],0);});
test('sparse and dense implementations agree on deterministic inputs and all neuron states',()=>{const a=new ConnectomeLIF(graph(),{seed:8}),b=new ConnectomeLIF(graph(),{seed:8,dense:true});for(let k=0;k<100;k++){a.step([{indices:[0],hz:100}]);b.step([{indices:[0],hz:100}]);assert.deepEqual(a.counts,b.counts);for(let i=0;i<3;i++){assert.ok(Math.abs(a.v[i]-b.v[i])<1e-10);assert.ok(Math.abs(a.g[i]-b.g[i])<1e-10);}}});
test('negative neurotransmitter sign inhibits rather than exciting a downstream cell',()=>{const g=graph();g.sign[0]=-1;const n=new ConnectomeLIF(g);n.stimulate(0);for(let i=0;i<40;i++)n.step();assert.equal(n.counts[1],0);assert.ok(n.v[1]<0);});
test('neural timing reports quantized delays and refuses unsupported timesteps',()=>{assert.throws(()=>new ConnectomeLIF(graph(),{dtMs:0}));const n=new ConnectomeLIF(graph());assert.equal(n.summary().effectiveDelayMs,2);assert.equal(n.summary().effectiveRefractoryMs,2.5);});
test('invalid neural inputs are rejected',()=>{const n=new ConnectomeLIF(graph());assert.throws(()=>n.stimulate(-1));assert.throws(()=>n.stimulate(0,NaN));assert.throws(()=>n.step([{indices:[0],hz:Infinity}]));});
test('neural environment cannot silently use the procedural opponent',()=>{assert.equal(config({insectModel:'neural'}).insectModel,'neural');assert.throws(()=>new Environment({insectModel:'neural'}),/Full neural assets/);});
