import {mkdir,rm,cp,writeFile} from 'node:fs/promises';
import {resolve} from 'node:path';
const root=resolve(import.meta.dirname,'..'),dist=resolve(root,'dist');
await rm(dist,{recursive:true,force:true});await mkdir(dist,{recursive:true});
for(const p of ['index.html','biology.html','neural.html','styles.css','src','docs'])await cp(resolve(root,p),resolve(dist,p),{recursive:true});
await mkdir(resolve(dist,'assets/neural'),{recursive:true});
for(const file of ['manifest.json','connectome.bin.gz','cells.json.gz'])await cp(resolve(root,'assets/neural',file),resolve(dist,'assets/neural',file));
await writeFile(resolve(dist,'.nojekyll'),'');
await writeFile(resolve(dist,'build.json'),JSON.stringify({version:'0.3.0',commit:process.env.GITHUB_SHA||'local',run:process.env.GITHUB_RUN_ID||null,built:new Date().toISOString()},null,2));
console.log('Built dist/: same-origin native modules. No runtime packages or external services.');
